<?php
$lang_text      = array(
    '500_desc' => 'Error with the Database.',
    '500_title' => 'This page is missing.',
    '404_desc' => 'This page is missing.',
    '404_title' => '404',
    '404_text' => 'Noooooo!!!',
    'Error_1' => 'Error!',
    'Error_2' => 'the information is not valid',
    'Home' =>'Home',
    'title_Downloader' =>'twitter online video downloader',
    'text_Downloader' =>'Fast and easy twitter video downloader',
	'Enter_url' => 'Enter the video link...',
	'text_0_bom' => 'Online video downloader',
	'text_1_bom' => 'We are an online video download and information backup tool, the best thing is that it is free and you will not have to install any other app on your mobile, so you will have much more space.',
    'text_2_bom' =>'Download Video Now!',
    'loader_input' =>'Processing...',
    'error_url_input' =>'At this time the service is not available, or the URL is broken.',
    'text_1' =>'1.Copy URL',
    'text_2' =>'Copy the URL of the video you want to download',
    'text_3' =>'2.Paste the URL',
    'text_4' =>'Paste the video url and wait a moment.',
    'text_5' =>'3.Download the video',
    'text_6' =>'Choose and download your favorite video easily and quickly',
    'Terms_of_Use' =>'Terms and Conditions',
    'Privacy_Palicy' =>'Privacy policies',
    'ERROR_SERVER_1' =>'Information found in the database.',
    'ERROR_SERVER_2' =>'Invalid url.',
    'ERROR_SERVER_3' =>'URL not available.',
    'ERROR_SERVER_4' =>'Information not found please try again.',
    'ERROR_SERVER_5' =>'ok',
);	
?>